name: Tim Bentinck
favicon: null
layout_spectrum: 0.90766
typography_spectrum: 0.018334651365876198
title: "Tim Bentinck's Website"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#623e2e'
    - '#d6a363'
    - '#915437'
    - '#f1c883'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
